name: catch
on:
  repository_dispatch:
    types: [ beacon ]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api repos/${{ github.repository }}/issues \
            -f title="${{ github.event.client_payload.title }}" \
            -f body="${{ github.event.client_payload.payload }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
