name: catch
on:
  repository_dispatch:
    types: [ beacon ]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-issue-from-file@v1
        with:
          title: ${{ github.event.client_payload.title }}
          content: ${{ github.event.client_payload.payload }}
          token: ${{ secrets.PAT }}
